/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_ALTERASTUBERR_H
# define HEADER_ALTERASTUBERR_H

# define ALTERASTUBerr(f, r) ERR_ALTERASTUB_error((f), (r), OPENSSL_FILE, OPENSSL_LINE)


# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_ALTERASTUB_strings(void);
void ERR_unload_ALTERASTUB_strings(void);
void ERR_ALTERASTUB_error(int function, int reason, char *file, int line);
# ifdef  __cplusplus
}
# endif

/*
 * ALTERASTUB function codes.
 */
# define ALTERASTUB_F_BIND_ALTERA_STUB                    100

/*
 * ALTERASTUB reason codes.
 */
# define ALTERASTUB_R_INIT_FAILED                         100

#endif
